### ISSUE TITLE
Webapp does not load in Android Browser Lightning 5.1.0

### ISSUE THREAD

**Issue by transalm** [WriteWiseCollabTech/WriteWise#11]
Tested on Huawei EMUI 12.0.0
https://github.com/anthonycr/Lightning-Browser

![Screenshot Start Page](https://github.com/user-attachments/assets/b388cdb2-5ccd-4bf3-ab87-1ca0040c2dfa)

![Screenshot_20241024_101024](https://github.com/user-attachments/assets/36db4a84-0f7f-4406-9e70-4ef0446a34a9)

**Comment by SamihMustafa** [comment]
needs a web3 wallet like metamask to get all the data

**Comment by transalm** [comment]
> needs a web3 wallet like metamask to get all the data so currently wont work on mobile

Thanks for clarifying, I notices the same behavior with [Foss Browser](https://codeberg.org/Gaukler_Faun/FOSS_Browser)
