### ISSUE TITLE
Webapp Screen 'Add Nomination' | Mandatory Field 'Title' Misbehaves

### ISSUE THREAD

**Issue by transalm** [WriteWiseCollabTech/WriteWise#8]
Nothing happens when typing in the field, but text typed (modified) in the field 'Description' shows up in the field 'Title'.
### Steps to reproduce
1. Open a competition in state 'Nominating'
2. Type some text or paste something from the clipboard in the field 'Title' it stays as it is.
3. Type something in field 'Description' the typed text appears in the field 'Title'
4. Try to modify the content of the field 'Title' nothing happens
5. Modify the field 'Description' the change appears in the field 'Title'

### Expected Behavior
- Text typed in the field 'Title' must be visible and modifiable
- Text typed in the field 'Description' must not alter the field 'Title'

**Comment by polatdk** [comment]
@transalm Love it! I just want to give you kodus for bug report syntax! I've been so much energy over the years get my teams to follow this :D

**Comment by transalm** [comment]
Likely I was [recording](https://github.com/user-attachments/assets/16c2ae4e-9601-491f-ac90-3ea0a6972574)


> I wasn't able to reproduce the bug, but I've added unique IDs to each form field, which should resolve the issue. If the problem persists, please let me know, along with details about your browser.

Likely I was [recording](https://github.com/user-attachments/assets/16c2ae4e-9601-491f-ac90-3ea0a6972574)
It looks like 912a8ee06ebc00de7c6d21e765d92eb5089df92b has fixed it.

I'll close the issue for now :shipit:
